### ISSUE TITLE
Expo.io

### ISSUE THREAD

**Issue by raphcadiz** [tabby-ai/react-native-example#12]
Do you have any sample for react-native app built with Expo. I tried to use the SDK but I'm getting several errors.

Also maybe you have SDK built with simple js rather than typescript. I think this is causing issue to app I'm trying to use this to.

**Comment by kuznetsov-from-wonderland** [comment]
Hey there! Actually tabby-react-native-sdk sound work just fine within expo env. Please check installation instructions
https://www.npmjs.com/package/tabby-react-native-sdk#requirements

Make sure you have `react-native-svg` and `react-native-webview` installed.
